version: '3.2'
services:
  database:
    image: quay.io/xiabai/postgres:latest
    ports:
      - "5432:5432"
    networks:
      factory-network:
        ipv4_address: 10.5.0.11

  factory:
    build:
      context: factory/
      dockerfile: src/main/docker/Dockerfile.jvm
    image: factory
    ports:
      - "8083:8083"
    networks:
      factory-network:
        ipv4_address: 10.5.0.7


  order:
    build:
      context: order/
      dockerfile: src/main/docker/Dockerfile.jvm
    image: order
    ports:
      - "8081:8081"
    networks:
      factory-network:
        ipv4_address: 10.5.0.5
  delivery:
    build:
      context: delivery/
      dockerfile: src/main/docker/Dockerfile.jvm
    image: delivery
    ports:
      - "8082:8082"
    networks:
      factory-network:
        ipv4_address: 10.5.0.6

networks:
  factory-network:
    external:
        name: local_network_dev
